.TH ngetlite 1 "16 May 2002"
.SH NAME
ngetlite \- retrieve files from NNTP hosts
.SH SYNOPSIS
.B ngetlite <listfiles...>
.SH DESCRIPTION
.B ngetlite
retrieves messages as described in each listfile.  Listfiles are generated with:
.br
.B nget -w <listfile> <retrieval args>
.PP
ngetlite is useful on computers with low ram or cpu, that can't handle the large cache
files needed for some groups.  You can run nget -w on some other computer and then do 
the actual downloading with ngetlite using very little resources.
.SH EXAMPLES
The following sequence of commands demonstrates a typical usage:
.br
nget -w foo.list -G alt.foo -r "\\.png"
.br
ngetlite foo.list
.br
nget -N -G alt.foo -r "\\.png"
.SH ENVIRONMENT
.PP
.IP "NGETLITE_TIMEOUT"
Socket timeout value in seconds.
.IP "NGETLITE_TRIES"
Max number of attempts per article.
.SH AUTHOR
Matthew Mueller <donut AT dakotacom.net>
.SH "SEE ALSO"
.BR nget (1)
